# Site settings
title: Hi, I'm Anthony. I build unique & interactive websites.
email: hianthonylan@gmail.com
baseurl:
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Anthonylan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedi
    url: https://linkedin.com/in/anthonycharles11
  - title: twitter
    url: https://twitter.com/anthonyxcharles
  - title: github
    url: https://github.com/anthonylan

# Build settings
markdown: kramdown
permalink: pretty
